# 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

# 筆記
###### loc iloc ix 介紹
loc ——通过行列的  标签  索引行数据

iloc——通过行列的  号索  引行数据

ix——通过行标签或者行号索引行数据


###### Note: 在 jupyter notebook 中，可以使用 ? 來調查函數的定義
?pd.read_csv

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
csv_data_path = os.path.join('.\data', 'application_test.csv')
print('Path of read in data: %s' %(csv_data_path))
csv_data = pd.read_csv(csv_data_path)

Path of read in data: .\data\application_test.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [3]:
#print(csv_data.columns.size)
print(csv_data.iloc[0,:].size)
print(csv_data.iloc[:,0].size)
print(csv_data.shape)

121
48744
(48744, 121)

#### 列出所有欄位

In [6]:
print(csv_data)

       SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0          100001         Cash loans           F            N               Y
1          100005         Cash loans           M            N               Y
2          100013         Cash loans           M            Y               Y
3          100028         Cash loans           F            N               Y
4          100038         Cash loans           M            Y               N
5          100042         Cash loans           F            Y               Y
6          100057         Cash loans           M            Y               Y
7          100065         Cash loans           M            N               Y
8          100066         Cash loans           F            N               Y
9          100067         Cash loans           F            Y               Y
10         100074         Cash loans           F            N               Y
11         100090         Cash loans           F            N               Y
12         100091         Cash loans           F            N               Y
13         100092         Cash loans           F            Y               Y
14         100106    Revolving loans           M            N               Y
15         100107         Cash loans           M            Y               Y
16         100109         Cash loans           F            Y               Y
17         100117         Cash loans           M            Y               Y
18         100128         Cash loans           F            Y               Y
19         100141         Cash loans           F            Y               Y
20         100150         Cash loans           F            N               Y
21         100168         Cash loans           F            N               Y
22         100169         Cash loans           F            N               Y
23         100170         Cash loans           M            N               Y
24         100171         Cash loans           M            Y               Y
25         100172         Cash loans           F            N               Y
26         100184         Cash loans           F            N               Y
27         100187         Cash loans           F            N               Y
28         100212         Cash loans           F            Y               N
29         100222         Cash loans           F            Y               Y
...           ...                ...         ...          ...             ...
48714      455963         Cash loans           F            N               N
48715      455965         Cash loans           M            Y               Y
48716      456007         Cash loans           M            N               Y
48717      456008         Cash loans           F            N               Y
48718      456009         Cash loans           F            N               Y
48719      456010         Cash loans           F            N               Y
48720      456011         Cash loans           F            Y               Y
48721      456013         Cash loans           F            N               Y
48722      456028         Cash loans           M            N               Y
48723      456058         Cash loans           F            N               N
48724      456111         Cash loans           F            N               Y
48725      456114         Cash loans           F            N               N
48726      456115         Cash loans           M            N               Y
48727      456116         Cash loans           F            N               N
48728      456119         Cash loans           F            N               Y
48729      456120         Cash loans           F            N               N
48730      456122         Cash loans           M            Y               N
48731      456123         Cash loans           F            Y               Y
48732      456166         Cash loans           F            N               Y
48733      456167         Cash loans           F            N               Y
48734      456168         Cash loans           F            N               Y
48735      456169         Cash loans           F            N               N
48736      456170         Cash loans           F            Y               Y
48737      456189         Cash loans           F            N               Y
48738      456202         Cash loans           F            Y               N
48739      456221         Cash loans           F            N               Y
48740      456222         Cash loans           F            N               N
48741      456223         Cash loans           F            Y               Y
48742      456224         Cash loans           M            N               N
48743      456250         Cash loans           F            Y               N

       CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                 0          135000.0    568800.0      20560.5
1                 0           99000.0    222768.0      17370.0
2                 0          202500.0    663264.0      69777.0
3                 2          315000.0   1575000.0      49018.5
4                 1          180000.0    625500.0      32067.0
5                 0          270000.0    959688.0      34600.5
6                 2          180000.0    499221.0      22117.5
7                 0          166500.0    180000.0      14220.0
8                 0          315000.0    364896.0      28957.5
9                 1          162000.0     45000.0       5337.0
10                0           67500.0    675000.0      25447.5
11                0          135000.0    261621.0      16848.0
12                0          247500.0    296280.0      23539.5
13                0           90000.0    360000.0      18535.5
14                0          180000.0    157500.0       7875.0
15                0          180000.0    296280.0      21690.0
16                0          202500.0    407520.0      26041.5
17                0           90000.0    499221.0      22117.5
18                1          225000.0    431280.0      23526.0
19                0          175500.0    478498.5      46741.5
20                0           99000.0    225000.0      19242.0
21                0          157500.0    266652.0      16443.0
22                0          135000.0    540000.0      27702.0
23                1          337500.0   1313212.5      42493.5
24                0          157500.0    539100.0      29245.5
25                0           76500.0    225000.0      12334.5
26                0          112500.0    256032.0      10759.5
27                0          225000.0    501363.0      25726.5
28                0           90000.0    450000.0      23107.5
29                0          360000.0    945000.0      34074.0
...             ...               ...         ...          ...
48714             1          360000.0    547272.0      43366.5
48715             0          315000.0    900000.0      57519.0
48716             0          135000.0    318645.0      16398.0
48717             0           81000.0    180000.0      13455.0
48718             0          225000.0    360000.0      19530.0
48719             1          112500.0    690313.5      35374.5
48720             1          171000.0    323460.0      23134.5
48721             1          130500.0    468333.0      37129.5
48722             0          220500.0    166500.0      13284.0
48723             1           67500.0    315000.0      16213.5
48724             1          112500.0    514710.0      17707.5
48725             0           45000.0    450000.0      24543.0
48726             1          225000.0   1002339.0      37917.0
48727             1          180000.0    149256.0      15291.0
48728             0          247500.0    685386.0      38398.5
48729             2           81000.0    135000.0      16020.0
48730             2          157500.0    445095.0      40824.0
48731             0          112500.0    450000.0      28890.0
48732             0          189000.0    479700.0      54382.5
48733             0          135000.0   1047771.0      37764.0
48734             0          135000.0    835686.0      46660.5
48735             0           85500.0    109008.0       7411.5
48736             0          157500.0    500490.0      48888.0
48737             0          270000.0    360000.0      28570.5
48738             3          135000.0    252022.5      23112.0
48739             0          121500.0    412560.0      17473.5
48740             2          157500.0    622413.0      31909.5
48741             1          202500.0    315000.0      33205.5
48742             0          225000.0    450000.0      25128.0
48743             0          135000.0    312768.0      24709.5

       AMT_GOODS_PRICE  ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19  \
0             450000.0  ...                0                0
1             180000.0  ...                0                0
2             630000.0  ...                0                0
3            1575000.0  ...                0                0
4             625500.0  ...                0                0
5             810000.0  ...                0                0
6             373500.0  ...                0                0
7             180000.0  ...                0                0
8             315000.0  ...                0                0
9              45000.0  ...                0                0
10            675000.0  ...                0                0
11            216000.0  ...                0                0
12            225000.0  ...                0                0
13            360000.0  ...                0                0
14            157500.0  ...                0                0
15            225000.0  ...                0                0
16            360000.0  ...                0                0
17            373500.0  ...                0                0
18            360000.0  ...                0                0
19            454500.0  ...                0                0
20            225000.0  ...                0                0
21            202500.0  ...                0                0
22            540000.0  ...                0                0
23           1012500.0  ...                0                0
24            450000.0  ...                0                0
25            225000.0  ...                0                0
26            180000.0  ...                0                0
27            418500.0  ...                0                0
28            450000.0  ...                0                0
29            945000.0  ...                0                0
...                ...  ...              ...              ...
48714         495000.0  ...                0                0
48715         900000.0  ...                0                0
48716         216000.0  ...                0                0
48717         180000.0  ...                0                0
48718         360000.0  ...                0                0
48719         549000.0  ...                0                0
48720         270000.0  ...                0                0
48721         382500.0  ...                0                0
48722         166500.0  ...                0                0
48723         315000.0  ...                0                0
48724         387000.0  ...                0                0
48725         450000.0  ...                0                0
48726         846000.0  ...                0                0
48727         135000.0  ...                0                0
48728         585000.0  ...                0                0
48729         135000.0  ...                0                0
48730         405000.0  ...                0                0
48731         450000.0  ...                0                0
48732         450000.0  ...                0                0
48733         904500.0  ...                0                0
48734         765000.0  ...                0                0
48735          90000.0  ...                0                0
48736         450000.0  ...                0                0
48737         360000.0  ...                0                0
48738         217561.5  ...                0                0
48739         270000.0  ...                0                0
48740         495000.0  ...                0                0
48741         315000.0  ...                0                0
48742         450000.0  ...                0                0
48743         270000.0  ...                0                0

      FLAG_DOCUMENT_20 FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR  \
0                    0                0                        0.0
1                    0                0                        0.0
2                    0                0                        0.0
3                    0                0                        0.0
4                    0                0                        NaN
5                    0                0                        0.0
6                    0                0                        0.0
7                    0                0                        0.0
8                    0                0                        0.0
9                    0                0                        0.0
10                   0                0                        0.0
11                   0                0                        0.0
12                   0                0                        0.0
13                   0                0                        0.0
14                   0                0                        0.0
15                   0                0                        0.0
16                   0                0                        0.0
17                   0                0                        0.0
18                   0                0                        0.0
19                   0                0                        NaN
20                   0                0                        0.0
21                   0                0                        0.0
22                   0                0                        0.0
23                   0                0                        0.0
24                   0                0                        0.0
25                   0                0                        0.0
26                   0                0                        0.0
27                   0                0                        0.0
28                   0                0                        0.0
29                   0                0                        0.0
...                ...              ...                        ...
48714                0                0                        0.0
48715                0                0                        0.0
48716                0                0                        NaN
48717                0                0                        0.0
48718                0                0                        0.0
48719                0                0                        0.0
48720                0                0                        0.0
48721                0                0                        0.0
48722                0                0                        0.0
48723                0                0                        0.0
48724                0                0                        0.0
48725                0                0                        0.0
48726                0                0                        0.0
48727                0                0                        0.0
48728                0                0                        0.0
48729                0                0                        NaN
48730                0                0                        0.0
48731                0                0                        0.0
48732                0                0                        0.0
48733                0                0                        0.0
48734                0                0                        0.0
48735                0                0                        NaN
48736                0                0                        0.0
48737                0                0                        0.0
48738                0                0                        0.0
48739                0                0                        0.0
48740                0                0                        NaN
48741                0                0                        0.0
48742                0                0                        0.0
48743                0                0                        0.0

       AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
0                            0.0                         0.0
1                            0.0                         0.0
2                            0.0                         0.0
3                            0.0                         0.0
4                            NaN                         NaN
5                            0.0                         0.0
6                            0.0                         0.0
7                            0.0                         0.0
8                            0.0                         0.0
9                            0.0                         0.0
10                           0.0                         0.0
11                           0.0                         0.0
12                           0.0                         0.0
13                           0.0                         0.0
14                           0.0                         0.0
15                           0.0                         0.0
16                           0.0                         0.0
17                           0.0                         0.0
18                           0.0                         0.0
19                           NaN                         NaN
20                           0.0                         0.0
21                           0.0                         0.0
22                           0.0                         0.0
23                           0.0                         0.0
24                           0.0                         0.0
25                           0.0                         0.0
26                           0.0                         0.0
27                           0.0                         0.0
28                           0.0                         0.0
29                           0.0                         0.0
...                          ...                         ...
48714                        0.0                         0.0
48715                        0.0                         0.0
48716                        NaN                         NaN
48717                        0.0                         0.0
48718                        0.0                         0.0
48719                        0.0                         0.0
48720                        0.0                         0.0
48721                        0.0                         0.0
48722                        0.0                         0.0
48723                        0.0                         0.0
48724                        0.0                         0.0
48725                        0.0                         0.0
48726                        0.0                         0.0
48727                        0.0                         0.0
48728                        0.0                         0.0
48729                        NaN                         NaN
48730                        0.0                         0.0
48731                        0.0                         0.0
48732                        0.0                         0.0
48733                        0.0                         0.0
48734                        0.0                         0.0

#### 截取部分資料

In [32]:
#print(csv_data([0:3]))
print("=====================================")
print(csv_data.iloc[0][0])
print("=====================================")
print(csv_data.iloc[3][3])
print("=====================================")
print(csv_data.iloc[3])

=====================================
100001
=====================================
N
=====================================
SK_ID_CURR                                           100028
NAME_CONTRACT_TYPE                               Cash loans
CODE_GENDER                                               F
FLAG_OWN_CAR                                              N
FLAG_OWN_REALTY                                           Y
CNT_CHILDREN                                              2
AMT_INCOME_TOTAL                                     315000
AMT_CREDIT                                        1.575e+06
AMT_ANNUITY                                         49018.5
AMT_GOODS_PRICE                                   1.575e+06
NAME_TYPE_SUITE                               Unaccompanied
NAME_INCOME_TYPE                                    Working
NAME_EDUCATION_TYPE           Secondary / secondary special
NAME_FAMILY_STATUS                                  Married
NAME_HOUSING_TYPE                         House / apartment
REGION_POPULATION_RELATIVE                         0.026392
DAYS_BIRTH                                           -13976
DAYS_EMPLOYED                                         -1866
DAYS_REGISTRATION                                     -2000
DAYS_ID_PUBLISH                                       -4208
OWN_CAR_AGE                                             NaN
FLAG_MOBIL                                                1
FLAG_EMP_PHONE                                            1
FLAG_WORK_PHONE                                           0
FLAG_CONT_MOBILE                                          1
FLAG_PHONE                                                1
FLAG_EMAIL                                                0
OCCUPATION_TYPE                                 Sales staff
CNT_FAM_MEMBERS                                           4
REGION_RATING_CLIENT                                      2
                                          ...
DEF_30_CNT_SOCIAL_CIRCLE                                  0
OBS_60_CNT_SOCIAL_CIRCLE                                  0
DEF_60_CNT_SOCIAL_CIRCLE                                  0
DAYS_LAST_PHONE_CHANGE                                -1805
FLAG_DOCUMENT_2                                           0
FLAG_DOCUMENT_3                                           1
FLAG_DOCUMENT_4                                           0
FLAG_DOCUMENT_5                                           0
FLAG_DOCUMENT_6                                           0
FLAG_DOCUMENT_7                                           0
FLAG_DOCUMENT_8                                           0
FLAG_DOCUMENT_9                                           0
FLAG_DOCUMENT_10                                          0
FLAG_DOCUMENT_11                                          0
FLAG_DOCUMENT_12                                          0
FLAG_DOCUMENT_13                                          0
FLAG_DOCUMENT_14                                          0
FLAG_DOCUMENT_15                                          0
FLAG_DOCUMENT_16                                          0
FLAG_DOCUMENT_17                                          0
FLAG_DOCUMENT_18                                          0
FLAG_DOCUMENT_19                                          0
FLAG_DOCUMENT_20                                          0
FLAG_DOCUMENT_21                                          0
AMT_REQ_CREDIT_BUREAU_HOUR                                0
AMT_REQ_CREDIT_BUREAU_DAY                                 0
AMT_REQ_CREDIT_BUREAU_WEEK                                0
AMT_REQ_CREDIT_BUREAU_MON                                 0
AMT_REQ_CREDIT_BUREAU_QRT                                 0
AMT_REQ_CREDIT_BUREAU_YEAR                                3
Name: 3, Length: 121, dtype: object

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子